name: Code Quality
on:
  pull_request:
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        id: biome
        run: biome ci --formatter-enabled=true --linter-enabled=false --organize-imports-enabled=false .
      - name: Add failure message
        if: failure()
        run: |
          echo "## Code Quality Check Failed" >> $GITHUB_STEP_SUMMARY
          echo "The Biome check has failed. Please review the output above and make necessary corrections." >> $GITHUB_STEP_SUMMARY
